forge "https://forge.puppetlabs.com"

mod "elasticsearch/elasticsearch"
mod "puppetlabs/java"
mod "puppetlabs/firewall"
mod "puppetlabs/stdlib"
mod "puppetlabs/apache"
mod "pdxcat/amanda"
mod "rtyler/jenkins"
mod "garethr/docker"
